[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmd = 'cd "FoodHub IIT Mandi Backend" && npm install --production'

[phases.build]
cmd = 'echo "No build step required for backend"'

[start]
cmd = 'cd "FoodHub IIT Mandi Backend" && npm start'
